### ISSUE TITLE
Noughts & Crosses 

### ISSUE THREAD

**Issue by MaddPaige** [MaddPaige/GrandmaMcgarvey#1]
I am wanting to make it so that my noughts and crosses can be played on my website. 

I want you to be able to click on each sections of the grid and have either a nought or cross added until there is a winner and then once the game is over for it to go empty again. 
![crosses](https://user-images.githubusercontent.com/43526594/66014046-e0d53600-e529-11e9-93d5-82a35b815e41.png)
![nought](https://user-images.githubusercontent.com/43526594/66014047-e16dcc80-e529-11e9-85f8-1d4a59fc7698.png)
![grid](https://user-images.githubusercontent.com/43526594/66014049-e16dcc80-e529-11e9-8009-f98b7f36c859.png)

**Comment by sehsarah** [comment]
Found an example https://codepen.io/coreydunkin/pen/zqrud - needs function added to empty once someone wins, but looks promising

**Comment by MaddPaige** [comment]
Thank you @sehsarah, I have added this code in but for some reason it is sitting behind everything even when i changed the z-index to 1. It is also not playing but this may be because it is sitting behind everything. Also where would I be able to add in my assets of the drawn noughts and crosses so the design matches my website. 
![Screen Shot 2019-10-15 at 9 02 03 AM](https://user-images.githubusercontent.com/43526594/66779377-7d380900-ef2a-11e9-9286-7732e37a9ece.png)

**Comment by sehsarah** [comment]
Issue 1 was jquery was missing

**Comment by sehsarah** [comment]
Issue 2 was there was a CSS syntax error

**Comment by sehsarah** [comment]
Remaining issues are:

1. Clicking on a square isn't super easy

Suggestions
- need to edit the custom mouse positioning @ellysmlly any tips?
- maybe elements are on top of it? but i think it's the mouse positioning issue

---

2. Edit and add the "Noughts wins" or "Cross wins" elements 

Suggestions
- Edit the HTML in the JS file
- Add the styling for your elements

---

3. Place the grids together (and edit the styling of the cubes to work with site design)

**Comment by sehsarah** [comment]
From what i saw in the demo this is fixed now, so closing the issue
