### ISSUE TITLE
Media Queries index 2 

### ISSUE THREAD

**Issue by MaddPaige** [MaddPaige/GrandmaMcgarvey#3]
For the second website page when i am trying to change my media queries for iPhone size my design is not changing at all. 
![Screen Shot 2019-10-10 at 11 58 05 AM](https://user-images.githubusercontent.com/43526594/66526457-3c6c7880-eb55-11e9-8a03-256f0198b65b.png)
@sehsarah

**Comment by sehsarah** [comment]
This one can be closed too if it is fixed @MaddPaige
